blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/gzamboni/open-gate-detector/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/gzamboni/open-gate-detector#readme
    about: Check the README for usage information.
